### ISSUE TITLE
HTTP status code messages are not passed through

### ISSUE THREAD

**Issue by grugnog** [youngj/httpserver#1]
I have been trying to get the tests for Drupal core to pass using the Drush runserver command, but the test below in error.test was failing because it was checking the HTTP status message, but httpserver was replacing it with the default one.

$this->assertTrue(strpos($this->drupalGetHeader(':status'), '500 Service unavailable (with message)'), t('Received expected HTTP status line.'));

According to http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6.1 localized messages are acceptable, and Apache passes them though, so I think that is the correct behavior. Hence I added code to parse out the message from the CGI and pass it through if non empty.

**Comment by grugnog** [comment]
Code is in pull request #2

**Comment by youngj** [comment]
merged 1aafcf37be301b6a0e7296af85192ff80e0760f7 . thanks!
